version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "github.com/olekukonko/tablewriter"
        versions: ["1.x"]
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "main"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "main"
    cooldown:
      default-days: 7

  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "github.com/olekukonko/tablewriter"
        versions: ["1.x"]
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "stable-5.21"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "stable-5.21"
    cooldown:
      default-days: 7

  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "github.com/olekukonko/tablewriter"
        versions: ["1.x"]
    labels: []
    schedule:
      interval: "weekly"
    # Security updates have a different PR limit policy (cannot be tweaked)
    # Preventing PR for regular updates will ensure only security related updates are proposed
    open-pull-requests-limit: 0
    target-branch: "stable-5.0"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "stable-5.0"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "stable-4.0"
    cooldown:
      default-days: 7
