version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "github.com/olekukonko/tablewriter"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "main"

  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "github.com/olekukonko/tablewriter"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "stable-5.21"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "stable-5.21"

  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "github.com/olekukonko/tablewriter"
    labels: []
    security-updates: true
    target-branch: "stable-5.0"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "stable-5.0"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    labels: []
    schedule:
      interval: "weekly"
    target-branch: "stable-4.0"
