name: Triaging
on:
  pull_request_target:
  issues:
    types:
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  label:
    if: github.event.pull_request
    permissions:
      contents: read  # for actions/labeler to determine modified files
      pull-requests: write  # for actions/labeler to add labels to PRs
    name: PR labels
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9  # v5.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
  notify:
    name: Notify
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
      - name: Notify
        uses: iamfj/action-label-notification@4e60f368a1f941089eeda54fdeb120f3f49ff66c  # v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mapping: >
            - label: Documentation
              recipients:
                - '@mionaalex'
